### ISSUE TITLE
Premium Accounts

### ISSUE THREAD

**Issue by Rekulous** [Rafiuth/Soggfy#1]
In the README, it says that this has not been tested on premium accounts.

I downloaded one song using the program and it works, but is there any possible risk to getting banned or having Soggfy possibly detected?

**Comment by Rafiuth** [comment]
I honestly don't know, i've been using it on my free account for a while and haven't had any issues.

It could be detected by spotify in theory, since it makes two additional requests to their api (track metadata and album cover) for each song using the same access token used by the client.

**Comment by Rekulous** [comment]
> I honestly don't know, i've been using it on my free account for a while and haven't had any issues.
> 
> It could be detected by spotify in theory, since it makes two additional requests to their api (track metadata and album cover) for each song using the same access token used by the client.

Yeah you are right about that. I'm worrying about the API Requests.

Even though it sends two additional requests, I think people who use premium will be fine if they use it every now and then, and not too often.

Its likely Spotify won't really care about users **for now...**      unless this thing blows up

**Comment by Rekulous** [comment]
> > I think people who use premium will be fine if they use it every now and then, and not too often.
> 
> You are right. Plus, i don't think it would be a smart move to ban a paying costumer lol. Either way, I may endup removing those requests all together at some point.
> 
> > Note: I forgot to mention that downloading 320K OGG works when using premium, so that's nice we can go over 160K
> 
> That great! I'll add that to the readme soon.

Ok, turns out this thing is probably blowing up right now because I noticed that 8 people just starred this thing in the span of 24 hours ago. Its probably from r/RIPREQUESTS on Reddit noticing this.
