### ISSUE TITLE
update 2.7.2 and spicetify issue

### ISSUE THREAD

**Issue by Masterload1975** [Rafiuth/Soggfy#100]
I installed new update and is working well. But if i install spicetify the soggfy button on top is away to setup everything.

How to fix this?

THX for the new version

**Comment by Rafiuth** [comment]
Thanks, this was a single CSS selector change and should be fixed in 2.7.3.

**Comment by mountaincastle47** [comment]
> Thanks, this was a single CSS selector change and should be fixed in 2.7.3.

hey man any update for this supposed quick fix?
