### ISSUE TITLE
Windows explorer thinks that the exported .ogg files are at 1411 kbps, when they are actually at 320 kbps

### ISSUE THREAD

**Issue by wayfarren** [Rafiuth/Soggfy#108]
I'm using the default configuration, and I have the output format set to "Original OGG", thinking this would give me the highest quality. It seems it did, and when running the exported track through [Spek](https://www.spek.cc/p/download), it shows that the track is 320kbps.

This is fine, but I fear the file may be much larger than it needs to be as a result. I'm a noob to audio stuff (like encoding) so bear with me, but I'm wondering if I can get the file any smaller (like bumping it down to 320kbps from 1411kbps) while keeping (even though the bitrate is technically at 320kbps) the maximum quality.

Or, is this already the smallest the file can be at the given audio quality of 320kbps, and windows explorer is just being weird?

**Comment by Rafiuth** [comment]
This is a bug in windows explorer, yes. For some reason they show the bitrate as if the files were uncompressed in some cases.
