### ISSUE TITLE
Back up releases of this project quickly

### ISSUE THREAD

**Issue by fulquit** [Rafiuth/Soggfy#11]
Spotify has taken down ZSpotify, i don't think it would take long before this also gets taken down.

**Comment by tacohitbox** [comment]
I have it backed up. Not linking it publicly because I don't want it to get taken down. I sent it into the Discord though.

**Comment by Rafiuth** [comment]
There are snapshots on the Wayback Machine and Software Heritage.

**Comment by tacohitbox** [comment]
If anyone wants my public backup, you can PM me on Discord for it
