### ISSUE TITLE
Unrecognised Audio Codec Error

### ISSUE THREAD

**Issue by ronnie40K** [Rafiuth/Soggfy#12]
![Screenshot (369)](https://user-images.githubusercontent.com/96225866/151566776-2545e621-fd5e-4dbc-b65a-2e5f93e17cf1.png)
This happens whenever a track has finished playing.

**Comment by Rafiuth** [comment]
Is this happening with all songs? I can't reproduce it, can you send the song link?

**Comment by ronnie40K** [comment]
Yeah, it seems to happen with all the songs. [Like this one for example.](https://open.spotify.com/track/59mpqaHJqbSublvEgM05O9)

**Comment by Rafiuth** [comment]
The track you linked is not available in my country, but I managed to reproduce this issue after setting "Streaming quality" to low. Could you try changing it to high and disabling "Auto adjust quality"?

**Comment by ronnie40K** [comment]
Oh lol I forgot I had set that to low. Changing that fixed it. Thanks and keep up the great work!
