### ISSUE TITLE
Metadata has stopped embedding

### ISSUE THREAD

**Issue by m1dst** [Rafiuth/Soggfy#13]
Just noticed that using 1.1.77.643 and latest release (v2.2.1), the metadata is not being embedded in the ogg as it was a few days ago.  Not sure if Spotify are fighting back with this or if you embed the metadata after stripping it but even the comment field is blank now.

Rebooted to be sure it wasn't just something memory resident.

**Comment by Rafiuth** [comment]
This usually happen when it can't find ffmpeg either on `%PATH%` or `Soggfy/ffmpeg/ffmpeg.exe`. Can you try running the DownloadFFmpeg script again?

**Comment by m1dst** [comment]
You are totally right.  I must have forgotten to redownload when I updated the release.  It also seems you need to restart Spotify too after download based on a quick test I did.  Hope this helps another person who forgets as I did.  I wonder if it is worth doing a check when the injector launches to warn the user it doesn't exist?

**Comment by Rafiuth** [comment]
> I wonder if it is worth doing a check when the injector launches to warn the user it doesn't exist?

There's indeed a check for this, but the warning is only written to the log file (older versions used to open a console window, so this was quite visible).

I'll add a warning on the injector in the next release.

**Comment by Rafiuth** [comment]
Warning implemented in 59ea70c3.
