### ISSUE TITLE
Special Characters

### ISSUE THREAD

**Issue by Itschotsch** [Rafiuth/Soggfy#14]
Some song titles contain very weird special characters or are extremely long, which is not allowed in directory or file names by the OS (Windows in my case). If the track template path in the Soggfy settings is something like `{artist_name}/{album_name}{multi_disc_path}/{track_num}. {track_name}.ogg`, Soggfy will try to name the file accordingly, which will obviously not work. I found that in this case, the file will not be saved at all. (But the green checkmark next to the song will sometimes still appear.) I suggest replacing all non-latin characters with a `-` or similar and limiting the file name length before saving the file.

**Comment by Rafiuth** [comment]
Support for long paths in added in 7aaadf1, please let me know if it fixes your issue.

[Binaries](https://github.com/Rafiuth/Soggfy/actions/runs/1844843031)
