### ISSUE TITLE
New Variable: playlist_num

### ISSUE THREAD

**Issue by SmilerRyan** [Rafiuth/Soggfy#16]
For songs that already exist in a plsylist more than once, this would be great to allow duplicates. In my case, there are a lot of songs that have the same file name but are different lengths (not the same exact song), so being able to save the order in the playlist would solve that and be a nice enhancement.

For example, these two songs in my liked songs would save as:
C:\Users\Ryan\Music\Soggfy\unknown\{playlist_num}. {artist_name} - {track_name}.ogg
C:\Users\Ryan\Music\Soggfy\unknown\316. 24kGoldn - DROPPED OUTTA COLLEGE.ogg
C:\Users\Ryan\Music\Soggfy\unknown\317. 24kGoldn - DROPPED OUTTA COLLEGE.ogg

![image](https://user-images.githubusercontent.com/14893385/154043060-4e803837-cc9f-478f-a0c6-67556a9bfdf7.png)

**Comment by Rafiuth** [comment]
Added in 85dd33d. Note that it ignores the playlist column sorting, the order is from oldest to newest track added.

Binaries will be available [here](https://github.com/Rafiuth/Soggfy/actions/runs/1855328798)
