### ISSUE TITLE
Old UI Support

### ISSUE THREAD

**Issue by hstntt** [Rafiuth/Soggfy#18]
Is it possible to add support for older versions? The old ui is cleaner, the title and artist columns are separated, plus the application uses less resources. Personally, I'm using 1.1.4, but if I remember correctly the last version before the redesign was 1.1.58.

**Comment by Rafiuth** [comment]
I think this would need a lot of work since there's a lot of hardcoded values for the current UI. I have no interest in implementing this, sorry.
