### ISSUE TITLE
Cover art not downloaded properly

### ISSUE THREAD

**Issue by ShowcaseKing** [Rafiuth/Soggfy#21]
Cover art which is automatically downloaded and embedded is only partially downloaded. Example:

![image](https://user-images.githubusercontent.com/65400142/156898507-036bf370-22c9-4d80-a093-455203b02af3.png)

OS: Windows 7
Spotify version: Spotify for Windows, 1.1.80.699
The latest release of the injector as of now.

**Comment by ShowcaseKing** [comment]
I forgot to mention that because your powershell script for some reason threw an error that I manually downloaded ffmpeg so maybe that is the cause of the problem.

**Comment by maliayas** [comment]
I have this, too. Same OS and version as the OP. Almost half of the tracks have this issue. Partial images gets embedded in ogg files. I don't have a clue as to why this happens.

**Comment by Rafiuth** [comment]
Is this happening with `cover.jpg` or just the embedded cover in the ogg file? I think it could be a ffmpeg issue or something in Spotify v1.80. I'd also appreciate if you guys can check if the [previous version](https://upgrade.scdn.co/upgrade/client/win32-x86/spotify_installer-1.1.79.763.gc2965cdf-21.exe) is also affected.

**Comment by maliayas** [comment]
Happening with `cover.jpg` as well. Exact same partial image is embedded in the ogg. It doesn't seem specific to ogg format, selecting mp3 doesn't fix the issue.

I don't think so but can it be a slow network issue? Does the software wait until the jpeg fully downloads? It being randomly occuring might mean that some error handling may be missing somewhere.

**Comment by ShowcaseKing** [comment]
I just tested it on the older version and it works exactly the same.

**Comment by ShowcaseKing** [comment]
> I just tested it on the older version and it works exactly the same.

By that I mean that it still downloads the images partially, in case I wasn't clear.

**Comment by Rafiuth** [comment]
I managed to reproduce this issue on a Windows 7 VM, I will try to find the cause tomorrow.

**Comment by Rafiuth** [comment]
This is apparently caused by uWebSockets v20.9.0, and weirdly enough, it only seems to affect Windows 7.
The bug was fixed in [v20.10.0](https://github.com/uNetworking/uWebSockets/releases/tag/v20.10.0), but it's not available on vcpkg yet, so I just downgraded to v20.8.0.

Can you confirm [this patch](https://github.com/Rafiuth/Soggfy/actions/runs/1953643896) works?

**Comment by maliayas** [comment]
Yes, it works! Thanks very much for the effort.

**Comment by ShowcaseKing** [comment]
I too can confirm it works now so therefore I will close this issue. Thank you for taking the time to fix it.
