### ISSUE TITLE
Track_num  error

### ISSUE THREAD

**Issue by DaBiszz** [Rafiuth/Soggfy#22]
{track_num} shows 1. for most songs

**Comment by Rafiuth** [comment]
Can you please post links to songs with this issue?

**Comment by DaBiszz** [comment]
![image](https://user-images.githubusercontent.com/90778672/156962606-f50bc471-c50f-4b47-af49-a33b06c59e93.png)
track template : {playlist_name}/{track_num}. {track_name} - {artist_name}.ogg
 https://open.spotify.com/playlist/37i9dQZEVXbMDoHDwVN2tF?si=23bed7e5ca7145f6

**Comment by Rafiuth** [comment]
`track_num` refers to the album track number. You can use `context_index` instead, see #16.
