### ISSUE TITLE
Conversion failed

### ISSUE THREAD

**Issue by microg850** [Rafiuth/Soggfy#28]
It says conversion failed (ffmpeg returned 1)

![image](https://user-images.githubusercontent.com/102790496/163999140-9b112ed2-fc15-4c5f-9bfb-46f1c72b8906.png)

**Comment by Rafiuth** [comment]
[This version](https://github.com/Rafiuth/Soggfy/releases/tag/v2.2.10) will give more details about ffmpeg errors, please try it and post the lines starting with `[ffmpeg.exe]` from the `log.txt` file.

**Comment by Rafiuth** [comment]
Closing as stale.
