### ISSUE TITLE
Project fails to inject hooks

### ISSUE THREAD

**Issue by justfoolingaround** [Rafiuth/Soggfy#29]
This issue doesn't seem all that common with the users as I can't seem to locate open or closed issues in regards to this.

![image](https://user-images.githubusercontent.com/79979949/165112335-fea9ab5d-7734-4ae0-83ad-03260694df68.png)

Unfortunately I can't pin point where this issue started since this has been happening for quite a while, with me on Soggfy 2.2.5. I thought it was associated with me not updating the project and just procrastinated updating. Now however, even after updating the project to [2.2.8](https://github.com/Rafiuth/Soggfy/releases/download/v2.2.8/Soggfy-2.2.8.zip), the issue still persists.

This issue persists even with me disabling Spicetify via `spicetify restore`.

Evident by the screenshot I'm on a Windows 11 PC. 

```
[DBG] FFmpeg path: C:\ProgramData\chocolatey\bin\ffmpeg.exe
[INF] Spotify version: 1.1.83.956
[DBG] Hook created: DecodeAudioData @ 0x9bdb7b
[ERR] Failed to install hooks: Fingerprint matches 0 locations, expected 1.

Try updating Soggfy.
```

Here's `log.txt`.

As I mentioned above, this issue doesn't seem common across devices, there might be something problematic on my end. It'd be great if I could get insights on how this is happening and even more great if there is a fix! Thanks!

**Comment by Rafiuth** [comment]
Hi, support for v1.1.83 was added in [v2.2.10](https://github.com/Rafiuth/Soggfy/releases/tag/v2.2.10).
