### ISSUE TITLE
Files always in .ogg

### ISSUE THREAD

**Issue by Ritew** [Rafiuth/Soggfy#30]
Hi,
I'm having problems trying to download .mp3 files, they are only downloaded in .ogg and without any metadata.
If you can check if there is a problem, thanks!

**Comment by Rafiuth** [comment]
This normally means that ffmpeg is missing. If you can't run the DownloadFFmpeg script, you'll need to do it manually:
- Download it from here: https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-n5.0-latest-win64-gpl-shared-5.0.zip
- Extract the `bin` folder into the soggfy directory, then rename it to `ffmpeg` (the final directory structure should look like `Soggfy/ffmpeg/ffmpeg.exe`).
