### ISSUE TITLE
Starring the repo threats this project

### ISSUE THREAD

**Issue by maliayas** [Rafiuth/Soggfy#34]
The more stars the higher chance this repo gets banned.

Shall we ask the star-gazers un-star the repo? 254 users at the moment, we can ping them here.

**Comment by maliayas** [comment]
Hi, may I kindly ask you to check this issue and consider __un-starring this project__?

Thanks in advance.

/ping

@Xt3ns1s @FurkanKutlu @ParasKPatel @lazios @ToxicSeinDad @dCo3lh0 @markjoshwel @myurar1a @Jerse1 @Reselim @TheNozomi @yoon4027 @Sxmurai @alexthemaster @pinkcig @wildpoptart @ArgX11 @kevintea @IsaacG96 @ksdrar @Kitsu-Shiro @ScottWilliamAnderson @spectrMeltdown @ImAiiR @SonicBoom2o @tylersulra @RyanU1328 @RBeesHup @erxson @Achraf-Elouardy @derdershat @LucaaFelix @kballar8 @cam1170 @D3rel @jamesdeluk @lexisother @qtekfun @Luiz-bro @Cynosphere @cheems @JakobLachermeier @smorgasbeerd @loopion @Nuc1eoN @ld3z @dennisstewart @GiorgioG

**Comment by qtekfun** [comment]
For sure. No prob

**Comment by Cynosphere** [comment]
I already have this repo mirrored off of GitHub, I don't care.

Please do not do this type of thing in the future, thanks.

**Comment by dfault-user** [comment]
I hope you explode

**Comment by yellowsink** [comment]
omw to directly email this to spotify support and say it gave me a virus

**Comment by yellowsink** [comment]
![image](https://user-images.githubusercontent.com/19270622/175407912-4d053661-a70e-4c8c-86f6-3b59125a3a1f.png)
balls

**Comment by pollen00** [comment]
starred

**Comment by yellowsink** [comment]
![image](https://user-images.githubusercontent.com/19270622/175418273-71a4f71f-9016-4797-8108-2b63dca7056a.png)
pov star
