### ISSUE TITLE
Ability to play tracks without overwriting (when skip disabled)

### ISSUE THREAD

**Issue by m1dst** [Rafiuth/Soggfy#36]
You can skip tracks already downloaded.  This is useful if all you want to do is rip anything you haven't already ripped.
If this is disabled, then all tracks will play.  This is also useful when you just want to play all tracks.

However, if you wish to listen to a playlist and rip anything you already haven't already downloaded, you can't cleanly do it.
The track will download and then transcoded even if it already exists.  Whilst this might not be an issue, the date of the file is overwritten making it harder to find "new" tracks but worse, if you have modified the file in some way, perhaps added additional metadata, it is lost.

Could you add another option "Overwrite downloaded tracks".  Using this in combination with Skip would be very flexible.

**Comment by Rafiuth** [comment]
Tracks are not supposed to get overwritten, there's a check before ffmpeg is even called.

Are there any warnings in `log.txt` like these?:
```
[INF] Saving track Bellevue Days - Pepper Tea
[DBG]   stream: playback_7d[...].dat
[INF] File 1. Pepper Tea.ogg already exists. Skipping conversion.
```

**Comment by m1dst** [comment]
You are indeed correct, conversion is skipped.  The "downloading" icon is what confused the situation.
