### ISSUE TITLE
I can't locate injector.exe

### ISSUE THREAD

**Issue by CyberWorrior2222** [Rafiuth/Soggfy#38]
I can see injector.cpp, injector.rc and injector.vsxproj tho (I'm new)

**Comment by SmilerRyan** [comment]
I assume you're trying to find the pre-compiled files, you can get them at the [releases page](https://github.com/Rafiuth/Soggfy/releases) for the project.
Currently the latest release (Soggfy-2.2.16.zip) has 6 files inside, including the injector.exe you're looking for.
