### ISSUE TITLE
spotify updates

### ISSUE THREAD

**Issue by hsl1** [Rafiuth/Soggfy#41]
i do run the block updates bat but it still updates when pc is rebooted.
Do i have to run block updates each time ?

![image](https://user-images.githubusercontent.com/11902467/178698075-fbbb4292-edad-40ca-aed3-078a91acf317.png)

**Comment by SmilerRyan** [comment]
The script should only need to be run once to block the update directory, unless they've figured out how to re-enable updates.

**Comment by hsl1** [comment]
Probably because it now updates and also dont skips ads....

**Comment by Rafiuth** [comment]
Haven't tested but [SpotX](https://github.com/amd64fox/SpotX) claims to be able to block updates, you could use it in the meantime.

**Comment by hsl1** [comment]
so it will always install .87 version?
however i tried this and seems to work however in spotify appears a small blue dot remebering to update but it wont autoupdate thats fine.

Hope that you add listen mode so it wont download all my songs  most of the times i just want to listen 
 https://spectrum.chat/spicetify/general/downgrade-spotify-block-updates~b182af17-79f8-4309-bfc1-3f3a8f3628d6?fbclid=IwAR1Uw2uk3b1ULG5eAfUc6J_aHwT4OCODCuq0E5XN5PSKd9tFDg2a5UhOTj

**Comment by Rafiuth** [comment]
This should no longer be a problem with https://github.com/Rafiuth/Soggfy/releases/tag/v2.3.0
