### ISSUE TITLE
[Feature Request] Pausing downloads

### ISSUE THREAD

**Issue by NotSpaulding** [Rafiuth/Soggfy#42]
## Reasoning
There are certain moments where I don't want to download songs, for example when I'm listening to my Discover Weekly.
Sometimes you just want to listen to a song just to check it out and not download it and having to relaunch Spotify just for that can be annoying.

## Pause downloads for session
A setting or a button to pause downloads for the current session I think would be great; it would work similarly to the Private session already in Spotify.

## Pause downloads on Private session
A setting for pausing downloads whenever Private session is enabled seems like a really good idea to me, considering it's a private session why would it download the songs you're listening to? Some people might not want this, so I think this would be best if it was toggleable.

## Conclusion
I think a setting for pausing downloads would really benefit Soggfy. Deleting files, skipping forward in a song to cancel the download or relaunching Spotify is cumbersome, so having a setting right into Soggfy to pause downloads would be less of an annoyance for the user.
Having both of the settings mentioned would, in my opinion, be the best way to go about this. Considering some people might not want to have Private sessions pause downloads and turning a setting on and off constantly can be annoying; so having an easily toggleable setting that is only enabled for the session would be really convenient.

**Comment by SmilerRyan** [comment]
Agreed, I would also like to be able to temporarilly turn off saving/speedup without relaunching the client.
Personally I'd add a pause (or enable Soggfy) toggle in the settings at the top for everything to be in one place.
