### ISSUE TITLE
Install.ps1 file crashes

### ISSUE THREAD

**Issue by shardool0d** [Rafiuth/Soggfy#48]
same as title

**Comment by Rafiuth** [comment]
Please take a look at the readme if you're willing to do a manual install.

**Comment by Mifo001** [comment]
**Ensure Execution Policy is Set to RemoteSigned:**
Before you can run the script, you need to ensure your PowerShell execution policy allows scripts to run. Search for Powershell in a similar way to the "Command Prompt" Open PowerShell as an administrator and run: Type the followling:

Set-ExecutionPolicy RemoteSigned

Then press enter, then select Y for yes, then just trying installing Soggfy again.

Hope it helps
