### ISSUE TITLE
Support "Enhanced" playlists

### ISSUE THREAD

**Issue by m1dst** [Rafiuth/Soggfy#49]
It seems there is a new enhanced mode for playlists where Spotify add to them.

Would be great if the UI could be updated to support this new mode.

![image](https://user-images.githubusercontent.com/958968/196477563-cc4bb114-9aac-4019-8d70-58487dd3dc02.png)

**Comment by Rafiuth** [comment]
For reference, the enhanced mode is not yet available for all users. I had to apply the SpotX patch and then replace the Soggfy Spotify install with the one at %appdata%.
