### ISSUE TITLE
DMCA

### ISSUE THREAD

**Issue by Rekulous** [Rafiuth/Soggfy#5]
When DMCA inevitably comes for this repo due to popularity rising, what will you do and what are your plans for this project?

A lot of people here seem to have found this tool recently from Reddit and other places.

**Comment by Rafiuth** [comment]
I've been thinking about moving to notabug.org, but they are not clear about their DMCA policy and it looks like they still take repos down for it. It also doesn't solve the inconvenience of users having to build from source.

deemix seems to be self hosting but that's a path I'm not willing to undertake...

**Comment by Rafiuth** [comment]
None at the moment.
