### ISSUE TITLE
Where is Injector.exe?

### ISSUE THREAD

**Issue by Khaine17** [Rafiuth/Soggfy#51]
Cannot locate this file in the latest build

**Comment by m1dst** [comment]
Check your virus quarantine. Windows Defender was deleting it for me. Had
to manually exclude it.

**Comment by SmilerRyan** [comment]
Can also confirm it's there, though scanning it for me didn't detect any viruses/malware.
![image](https://user-images.githubusercontent.com/14893385/199131243-2fc090b6-9a6e-4560-a360-9591b35fcec7.png)

**Comment by m1dst** [comment]
defender silently quarantined it for me. Was a little confusing when it
happened.

**Comment by Rafiuth** [comment]
Please reopen if this is still an issue.
