### ISSUE TITLE
FLAC support?

### ISSUE THREAD

**Issue by th1nhhdk** [Rafiuth/Soggfy#54]

**Comment by SmilerRyan** [comment]
Seems that the original OGG files can be converted to FLAC (including album art) with ffmpeg.
The command I did to test it: ``ffmpeg -i "Train - Drive By.ogg" "Train - Drive By.flac"``
With this, It seems all that needs adding is the extension to the list of available formats.

![image](https://user-images.githubusercontent.com/14893385/199418855-b588632f-8411-417a-8ccd-eb4021f8fd21.png)

**Comment by Rafiuth** [comment]
Worth noting that Spotify does not currently provide lossless tracks, converting the already lossy OGG to FLAC would only bloat the file size for no benefit. If this is for compatibility, I believe the extension can be changed in config.json, provided you also adjust the ffmpeg arguments.
