### ISSUE TITLE
injector closes after spotify opens.

### ISSUE THREAD

**Issue by Khaine17** [Rafiuth/Soggfy#55]
I see where when I hit play, the song plays as normal and files are created in the newly created "temp" directory, but are they supposed to convert to mp3 aftewards? nothing happens and I just have lots of these temp files that are ffmd extension

**Comment by Rafiuth** [comment]
Can you please check the log.txt file for errors? Someone else had this issue and it was fixed by disabling pihole/whitelisting `spclient.wg.spotify.com`.

**Comment by Khaine17** [comment]
no errors within the log
[log.txt](https://github.com/Rafiuth/Soggfy/files/9924777/log.txt)

**Comment by lferraro** [comment]
@Khaine17 converted tracks are not in the "temp" directory, but you will find them in your default Music directory of Windows, where the Soggy directory is created by the injector to collect converted tracks.

**Comment by Khaine17** [comment]
> @Khaine17 converted tracks are not in the "temp" directory, but you will find them in your default Music directory of Windows, where the Soggy directory is created by the injector to collect converted tracks.
> 
> @Rafiuth maybe this should be clarified in your README

Oh wow, thank you so much @lferraro this was where the files were! Much appreciated
