### ISSUE TITLE
request: Add {playlist_track_num} to track template variables

### ISSUE THREAD

**Issue by cjl4hd** [Rafiuth/Soggfy#58]
I would like being able to download playlists as-is, in the order that I created them in Spotify. This way it will be possible to save each playlist in its own folder and easily playable in the order of the original playlist.

**Comment by Rafiuth** [comment]
This already exists as `{context_index}` (you might be interested in `{context_name}` as well). Note that it will ignore column sorting and output `0` for tracks added in the queue.

Ref: #16
