### ISSUE TITLE
request: option to embed metadata with .ogg format

### ISSUE THREAD

**Issue by AfthenDEV** [Rafiuth/Soggfy#59]
It would be nice if the metadata (such as the track number, the title, the album, etc) is also embedded when a song is downloaded. Because currently, all songs have no metadata in them:
![Screenshot 2022-11-17 101151](https://user-images.githubusercontent.com/94941720/202337455-b78b8d9c-a573-4692-b9a5-891c3ceb27ad.png)

I can't find the option for this in the Soggfy settings. I was wondering if this feature is implemented in already or is planned in the future. If it is implemented already, can someone please point me in the right direction for how to enable it?

Thanks!

**Comment by SmilerRyan** [comment]
Which file format are you trying to save in? For me I use the mp3 option which has the track details stored in them just fine.

![image](https://user-images.githubusercontent.com/14893385/202452217-c112610b-b73b-4b63-a339-03be75629249.png)

**Comment by AfthenDEV** [comment]
I think it was .ogg since it's the default option. I'll try switching to .mp3 to see if it works. I still wish it works even when saving in the .ogg format though.

Thanks!

**Comment by Rafiuth** [comment]
Windows is quite bad when it comes to displaying metadata from OGG files, maybe try checking with a player like foobar2000/MusicBee/MPCHC/VLC (or really any other).

This could also be due to ffmpeg missing, you can check the log.txt file for errors or just change the output format and see if it works.
