### ISSUE TITLE
Can't save music: "Unrecognized audio codec"

### ISSUE THREAD

**Issue by ItsIgnacioPortal** [Rafiuth/Soggfy#64]
When playback of a song finishes, in the song list I can see a red cross. Hovering over this red cross shows the message `Unrecognized audio codec`, and no file is saved.

I have the defaut settings and I'm using Soggfy v2.5.0

**Comment by danieljg** [comment]
I'm having the same issue since a few days ago.  It took me a while to figure out what was going on, as I was downloading a podcast and the red cross doesn't seem to appear there (only in regular music tracks, but both kinds of files fail to download).

**Comment by asdqwe190** [comment]
same here. I'm having the same issue. I was using the old version of spotify and soggfy so I tried to download the latest one, some of the songs are able to download but most of them are getting unrecognized audio codec

**Comment by Rafiuth** [comment]
Dupe of #12? Spotify switches to a different codec if the streaming quality setting is not set to high, which is not supported by Soggfy.

**Comment by ItsIgnacioPortal** [comment]
> Dupe of #12? Spotify switches to a different codec if the streaming quality setting is not set to high/very high, which is not supported by Soggfy (iirc, it's low quality AAC wrapped in a proprietary file format, I don't see any reason to bother supporting it).

That was it. I changed streaming quality from "automatic" to "high" and soggfy started working again. Thanks!
