### ISSUE TITLE
Powershell error

### ISSUE THREAD

**Issue by NicolasPL64** [Rafiuth/Soggfy#7]
I'm getting this error when running DownloadFFmpeg
![image](https://user-images.githubusercontent.com/31411531/139569706-4f552a8a-b46c-415f-b2d3-2121bb761810.png)

**Comment by Rafiuth** [comment]
Thanks for reporting this. I've released a update with a fix for this: [v1.4.7-pre](https://github.com/Rafiuth/Soggfy/releases/tag/v1.4.7-pre)
