### ISSUE TITLE
Experiences with ViWizard Audio converter?

### ISSUE THREAD

**Issue by Lucyy-cloud** [Rafiuth/Soggfy#79]
This music converter, which is available for both free and Premium users, can help you download your favorite songs and playlists from the most popular music streaming services.[ ViWizard Audio Converter ](https://www.viwizard.com/audio-converter)is an essential multitasking tool that's perfect for the conversion of audio files.

**Comment by Rafiuth** [comment]
If not for SEO manipulation, OP must be really desperate to be spamming their paid app across [several](https://github.com/search?q=ViWizard&type=issues) random FOSS GitHub issue trackers.

[According to reddit](https://www.reddit.com/r/Tuneskit/comments/qp78b7/comment/hjw45js/), ViWizard is just an updated tuneskit version, which was known for getting Spotify accounts suspended. Not that there isn't any risk with Soggfy, but there are lots of better and free options out there.

**Comment by Lucyy-cloud** [comment]
> If not for SEO manipulation, OP must be really desperate to be spamming their paid app across [several](https://github.com/search?q=ViWizard&type=issues) random FOSS GitHub issue trackers.
> 
> [According to reddit](https://www.reddit.com/r/Tuneskit/comments/qp78b7/comment/hjw45js/), ViWizard is just an updated tuneskit version, which was known for getting Spotify accounts suspended. Not that there isn't any risk with Soggfy, but there are lots of better and free options out there.

The ViWizard version will not cause the Spotify account to be suspended, which is sensational. My friends around me all use the ViWizard audio converter to download Apple music, and feel very good.
