### ISSUE TITLE
Downloading songs that are already downloaded?

### ISSUE THREAD

**Issue by Weegee30** [Rafiuth/Soggfy#84]
Would it be possible to make an update so you could be able to download or extract songs that are already downloaded with a premium account? There are some files in `%localappdata%\Spotify\Storage` but they're encrypted. This would be a huge feature to add.

Also I just found this tool yesterday and it's been working like a charm! Thank you for making this useful tool!

**Comment by SmilerRyan** [comment]
From the sounds of it, you'd just want to go into offline mode on spotify (assuming you want to free your account), and play them the same as normal songs. Playing caches files should work the same way. i've had no problem setting the playback speed to 200x (click on the textbox next to the slider in the settings) so it just loads and extracts as fast as it can.

**Comment by Weegee30** [comment]
> From the sounds of it, you'd just want to go into offline mode on spotify (assuming you want to free your account), and play them the same as normal songs. Playing caches files should work the same way. i've had no problem setting the playback speed to 200x (click on the textbox next to the slider in the settings) so it just loads and extracts as fast as it can.

Thank you so much! I had no idea it was that simple. I downloaded an album, switched to offline mode, and I was able to stream and download the tracks at 200x speed like you said. Maybe add this information to the `README.md` for premium users to know about this, because I tried downloading the tracks with just no internet (i didn't bother to turn on offline mode) and it wouldn't download the stream.

Maybe in the future you could add a warning or pop-up of some kind or maybe a toggle setting to disable going past 1x, if people skim through the readme, they might not realize that past 1x playback speed might get their account banned. Not only that, I accidently increased the playback setting, and I was a little worried, it was just one time so I should be fine.

Thank You for the help!
