### ISSUE TITLE
spicetify to work in 2.5.1?

### ISSUE THREAD

**Issue by Masterload1975** [Rafiuth/Soggfy#88]
Hi

Great to see you back with a new Release. THX

Can you please fix spicetify to work in 2.5.1?

The Marketplace is not visible.

Greets

**Comment by Masterload1975** [comment]
I get it to work

**Comment by Rafiuth** [comment]
Is this the same issue as #56? I'll add that patch soon if I get around to updating the mod to the newest Spotify (which is still stuck on v1.1.97 as of release 2.5.1).

**Comment by Masterload1975** [comment]
Yes it is the Same issue. And in Soggfy\Spotify\ must the file "prefs" be present. With login settings. Setup spicetify cant setup correct without prefs

**Comment by Rafiuth** [comment]
This should be fixed in [v2.7.0+](https://github.com/Rafiuth/Soggfy/releases).
