### ISSUE TITLE
The application was unable to start correctly (0xc000007b).

### ISSUE THREAD

**Issue by tacohitbox** [Rafiuth/Soggfy#9]
I downloaded Spotify and Soggify within a Windows 10 VM, downloaded all the DLLs it asked, and it gave me this error. I tried all solutions with similar error codes to no avail.

![image](https://user-images.githubusercontent.com/87399016/145753963-cd6782ba-fdc7-4abc-9235-db5f3b59a8a0.png)

If this helps, here's all the programs I currently have installed.

![image](https://user-images.githubusercontent.com/87399016/145754182-247fc9ab-6a68-4469-8184-fd968e0f6ffc.png)

**Comment by tacohitbox** [comment]
Also I installed it from the link given in the repo, shown highlighted below.
![image](https://user-images.githubusercontent.com/87399016/145754475-efcbab5d-7266-4724-8dd5-4f49f17d1212.png)

**Comment by Rafiuth** [comment]
I see you have the x64 C++ runtimes installed, but not the x86 versions. Can you try installing it? https://aka.ms/vs/17/release/vc_redist.x86.exe

You might also need to delete that vcruntime DLL from the soggfy folder, to prevent it from conflicting with the installed runtime.

Let me know if this works.

**Comment by tacohitbox** [comment]
That worked! Thanks for the help!
