### ISSUE TITLE
Error: Couldn't find target process in 2.7.1

### ISSUE THREAD

**Issue by Masterload1975** [Rafiuth/Soggfy#92]
Update and complete new install not working. If i start Injector.exe "Couldn't find target process"

**Comment by Rafiuth** [comment]
After running the install script in v2.7.1, Soggfy should just work whenever you launch Spotify. The injector was left as a last resort thing and it now requires that Spotify be open before using it.

Is the Install.cmd script not working for you?

**Comment by Masterload1975** [comment]
Working now perfect. I thought I had to start Injector.exe. Last Version i always starting Spotify over Injector.exe

**Comment by Rafiuth** [comment]
Alright, I'll close this but feel free to open another thread if you have other problems.
