### ISSUE TITLE
Error with uninstalling 

### ISSUE THREAD

**Issue by CptTziann** [Rafiuth/Soggfy#95]
This is the prompt i get when trying to uninstall the latest version.
C:\Users\name\Downloads\Soggfy-2.7.1\Soggfy-2.7.1>del C:\Users\name\AppData\Roaming\Spotify\dpapi.dll
Could Not Find C:\Users\harry\AppData\Roaming\Spotify\dpapi.dll

C:\Users\name\Downloads\Soggfy-2.7.1\Soggfy-2.7.1>del C:\Users\name\AppData\Roaming\Spotify\SoggfyUIC.js
Could Not Find C:\Users\harry\AppData\Roaming\Spotify\SoggfyUIC.js

C:\Users\name\Downloads\Soggfy-2.7.1\Soggfy-2.7.1>rmdir /q /s C:\Users\name\AppData\Local\Soggfy
The system cannot find the file specified.

C:\Users\name\Downloads\Soggfy-2.7.1\Soggfy-2.7.1>pause
Press any key to continue . . .

**Comment by Rafiuth** [comment]
This is normal and will happen if soggfy hasn't been installed before.
